# Generated by Django 5.0.6 on 2024-07-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions_user_product',
            old_name='Datetime',
            new_name='datetime',
        ),
    ]
