# Generated by Django 5.0.6 on 2024-07-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('base_price', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('public sale', 'public sale'), ('English auction', 'English auction')], max_length=40)),
            ],
        ),
    ]
