# Generated by Django 5.0.4 on 2024-04-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productorservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorservice',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
