# Generated by Django 5.0.6 on 2024-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
